setup: true
version: 2.1
Branches:
  only:
    - main
orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable" #build docker image
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install #install frontend dependencies
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install #install backend dependencies
          command: |
            npm run api:install
      - run:
          name: Front-End Build #build api to be smaller
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build #build angular app into wwww folder
          command: |
            npm run api:build
      - run:
          name: Deploy api # deploy api on eb
          command: |
            npm run api:deploy
      - run:
          name: Deploy frontend # deploy frontend on s3 bucket
          command: |
            npm run frontend:deploy
